events {}

http {

    geo $block_ru {
        default 0;

        # тестовый IP
        172.20.0.1 1;
    }

    server {
        listen 80;
        listen [::]:80;

        charset utf-8;

        location = /access-denied {
            default_type text/html;
            return 200 "
            <html>
                <body style='text-align:center;margin-top:100px;font-family:sans-serif'>
                    <h1>ВАМ СЮДА НЕЛЬЗЯ</h1>
                </body>
            </html>";
        }

        location / {

            if ($block_ru) {
                return 302 /access-denied;
            }

            proxy_pass http://parser_app:8000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}